Traceback (most recent call last):
  File "solve.py", line 24, in <module>
    is_resume = sys.argv[2] == '-resume' and int(sys.argv[3])%4000 == 0
IndexError: list index out of range
