Traceback (most recent call last):
  File "solve.py", line 25, in <module>
    iteration = int(sys.argv[3])
IndexError: list index out of range
